FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

# Python 2.7 or 3.5 is supported by Ubuntu Xenial out of the box
RUN apt-get update && apt-get install -y --allow-downgrades --allow-change-held-packages --no-install-recommends \
        build-essential \
        cmake \
        git \
        curl \
        vim \
        wget \
        ca-certificates \
        libjpeg-dev \
        libpng-dev

# Install Open MPI
RUN mkdir /tmp/openmpi && \
    cd /tmp/openmpi && \
    wget https://www.open-mpi.org/software/ompi/v4.0/downloads/openmpi-4.0.0.tar.gz && \
    tar zxf openmpi-4.0.0.tar.gz && \
    cd openmpi-4.0.0 && \
    ./configure --enable-orterun-prefix-by-default && \
    make -j $(nproc) all && \
    make install && \
    ldconfig && \
    rm -rf /tmp/openmpi

ENV MV=3
RUN wget --quiet https://repo.continuum.io/miniconda/Miniconda$MV-latest-Linux-x86_64.sh && \
    chmod +x Miniconda$MV-latest-Linux-x86_64.sh && \
    ./Miniconda$MV-latest-Linux-x86_64.sh -b -p /opt/conda && \
    rm Miniconda$MV-latest-Linux-x86_64.sh

ENV PATH="/opt/conda/bin:$PATH"
ENV CMAKE_PREFIX_PATH="/opt/conda"

RUN conda update conda
RUN pip install --upgrade pip
RUN conda create -n py35 python=3.5
# RUN conda activate py35

ENV PATH="/opt/conda/envs/py35/bin:$PATH"
ENV CMAKE_PREFIX_PATH="/opt/conda/envs/py35"

RUN pip install --upgrade pip
RUN conda install conda 

ENV TENSORFLOW_VERSION=1.12.0
ENV PYTORCH_VERSION=1.1.0
ENV TORCHVISION_VERSION=0.2.2.post3
ENV MXNET_VERSION=1.4.1

# RUN ln -s /usr/bin/python${PYTHON_VERSION} /usr/bin/python
# RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
#     python get-pip.py && \
#     rm get-pip.py


# Install TensorFlow, Keras, PyTorch and MXNet
RUN pip install 'numpy<1.15.0' tensorflow-gpu==${TENSORFLOW_VERSION} keras h5py torch==${PYTORCH_VERSION} torchvision==${TORCHVISION_VERSION} mxnet-cu90==${MXNET_VERSION}


# Install Horovod, temporarily using CUDA stubs
RUN ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs && \
    HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_MXNET=1 pip install --no-cache-dir horovod && \
    ldconfig

# Install OpenSSH for MPI to communicate between containers
RUN apt-get install -y --no-install-recommends openssh-client openssh-server && \
    mkdir -p /var/run/sshd

# Allow OpenSSH to talk to containers without asking for confirmation
RUN cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new && \
    echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new && \
    mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config

# Download examples
RUN apt-get install -y --no-install-recommends subversion && \
    svn checkout https://github.com/horovod/horovod/trunk/examples && \
    rm -rf /examples/.svn

WORKDIR "/examples"

